### ISSUE TITLE
App not executed in Marshmallow, is there any solution.Please help me.....

### ISSUE THREAD

**Issue by sathishmscict** [amitshekhariitbhu/AppLock#1]
11-17 11:05:58.437 17007-17007/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: applock.mindorks.com.applock, PID: 17007
                                                   java.lang.RuntimeException: Unable to create service applock.mindorks.com.applock.services.AppCheckServices: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@19bd4cb -- permission denied for this window type
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
                                                       at android.app.ActivityThread.-wrap4(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@19bd4cb -- permission denied for this window type
                                                       at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
                                                       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
                                                       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                       at applock.mindorks.com.applock.services.AppCheckServices.onCreate(AppCheckServices.java:88)
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
                                                       at android.app.ActivityThread.-wrap4(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
11-17 11:05:59.315 2167-14277/? E/AudioRecord-JNI: Error -4 during AudioRecord native read
11-17 11:05:59.529 204-17075/? E/ACDB-LOADER: Error: ACDB AudProc vol returned = -19
11-17 11:06:02.650 17080-17080/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: applock.mindorks.com.applock, PID: 17080
                                                   java.lang.RuntimeException: Unable to create service applock.mindorks.com.applock.services.AppCheckServices: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@cdedc51 -- permission denied for this window type
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
                                                       at android.app.ActivityThread.-wrap4(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@cdedc51 -- permission denied for this window type
                                                       at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
                                                       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
                                                       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                       at applock.mindorks.com.applock.services.AppCheckServices.onCreate(AppCheckServices.java:88)
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
                                                       at android.app.ActivityThread.-wrap4(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
11-17 11:06:02.739 2167-17006/? E/AudioRecord-JNI: Error -4 during AudioRecord native read
11-17 11:06:03.728 204-17125/? E/ACDB-LOADER: Error: ACDB AudProc vol returned = -19
11-17 11:06:56.745 17139-17139/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: applock.mindorks.com.applock, PID: 17139
                                                   java.lang.RuntimeException: Unable to create service applock.mindorks.com.applock.services.AppCheckServices: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@cdedc51 -- permission denied for this window type
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
                                                       at android.app.ActivityThread.-wrap4(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@cdedc51 -- permission denied for this window type
                                                       at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
                                                       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
                                                       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                       at applock.mindorks.com.applock.services.AppCheckServices.onCreate(AppCheckServices.java:88)
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
                                                       at android.app.ActivityThread.-wrap4(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by amitshekhariitbhu** [comment]
This application is very old. I am not looking forward to develop it more. 
FYI : you can use accessibility API provided by android to build AppLock applications.

Refer the link
https://developer.android.com/guide/topics/ui/accessibility/index.html

Thanks
Amit Shekhar

**Comment by sathishmscict** [comment]
Thank you for your response.
